using System.Web.UI;
using DevExpress.Web.ASPxClasses;
using WebAppCommons.Classes.Resources.ResourceHelpers;

[assembly: WebResourceAssembly(101)]
[assembly: WebResource("WebAreaCommons.Images.nf-logo.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.admin-area-logo.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.client-area-logo.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.taxation-area-logo.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.page-menu-gutter.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-vertical.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-vertical-disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-vertical-hottracked.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-horizontal.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-horizontal-disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.popout-horizontal-hottracked.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.menu-separator.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnNew.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnEdit.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnDelete.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnView.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnRefresh.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnSearch.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnSeparator.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnExpandAll.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnExpandAll_Disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnCollapseAll.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnCollapseAll_Disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnDetail.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnAddTest.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnDownload.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnDownloadAll.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnReport.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_admin_area.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_client_area.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_taxation_area.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.operator_client_area.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.tax_inspector.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_admin_area_disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_client_area_disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.admin_taxation_area_disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.operator_client_area_disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.Roles.tax_inspector_disabled.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.EDocumentSignatureStatus.fail.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.EDocumentSignatureStatus.success.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.EDocumentSignatureStatus.unknown.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.EDocumentSignatureStatus.warning.png", "image/png")]
[assembly: WebResource("WebAreaCommons.Images.btnClose.png", "image/png")]

[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoBold.RobotoBold.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoBold.RobotoBold.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoBold.RobotoBold.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoLight.RobotoLight.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoLight.RobotoLight.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoLight.RobotoLight.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoMedium.RobotoMedium.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoMedium.RobotoMedium.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoMedium.RobotoMedium.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoRegular.RobotoRegular.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoRegular.RobotoRegular.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.Roboto.RobotoRegular.RobotoRegular.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIBold.SegoeUIBold.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIBold.SegoeUIBold.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIBold.SegoeUIBold.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIItalic.SegoeUIItalic.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIItalic.SegoeUIItalic.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIItalic.SegoeUIItalic.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUILight.SegoeUILight.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUILight.SegoeUILight.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUILight.SegoeUILight.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIRegular.SegoeUIRegular.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIRegular.SegoeUIRegular.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUIRegular.SegoeUIRegular.woff", "font/woff")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUISemiBold.SegoeUISemiBold.eot", "font/eot")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUISemiBold.SegoeUISemiBold.ttf", "font/ttf")]
[assembly: WebResource("WebAreaCommons.Fonts.SegoeUI.SegoeUISemiBold.SegoeUISemiBold.woff", "font/woff")]

[assembly: WebResource("WebAreaCommons.Styles.embedded-fonts-stylesheet.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebAreaCommons.Styles.base-stylesheet.css", "text/css")]
[assembly: WebResource("WebAreaCommons.Styles.IE8.base-stylesheet.css", "text/css")]

[assembly: WebResource("WebAreaCommons.Scripts.Executables.attach-doublescroll.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.Executables.nocookie-handling.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.Executables.page-minheight.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.Executables.window-scroll-blinking-fix.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.Executables.page-functions.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.Controls.ASPx.CommonASPxGridView.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.CryptoCore.deployJava.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.CryptoCore.javaAppletHelper.js", "text/javascript")]
[assembly: WebResource("WebAreaCommons.Scripts.CryptoCore.webtoolkit.base64.js", "text/javascript")]

[assembly: WebResource("WebAreaCommons.Localization.base-localizationdata.xml", "text/xml")]

namespace WebAreaCommons.ResourceRepositories
{
    public static class WebAreaCommonResources
    {
        public static string ProvideURLFor(string resourceName)
        {
            return ResourceHelper.GetWebResourceUrl(typeof(WebAreaCommonResources), resourceName.TryToFix("WebAreaCommons"));
        }
    }
}