//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtecTeamFlasher.VtecTeamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VtecTeamService.IVtecTeamWebService")]
    public interface IVtecTeamWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtecTeamWebService/Authenticate", ReplyAction="http://tempuri.org/IVtecTeamWebService/AuthenticateResponse")]
        ClientAndServerCommons.AuthInfoResult Authenticate(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtecTeamWebService/Authenticate", ReplyAction="http://tempuri.org/IVtecTeamWebService/AuthenticateResponse")]
        System.Threading.Tasks.Task<ClientAndServerCommons.AuthInfoResult> AuthenticateAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtecTeamWebService/SignOut", ReplyAction="http://tempuri.org/IVtecTeamWebService/SignOutResponse")]
        void SignOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtecTeamWebService/SignOut", ReplyAction="http://tempuri.org/IVtecTeamWebService/SignOutResponse")]
        System.Threading.Tasks.Task SignOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVtecTeamWebServiceChannel : VtecTeamFlasher.VtecTeamService.IVtecTeamWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VtecTeamWebServiceClient : System.ServiceModel.ClientBase<VtecTeamFlasher.VtecTeamService.IVtecTeamWebService>, VtecTeamFlasher.VtecTeamService.IVtecTeamWebService {
        
        public VtecTeamWebServiceClient() {
        }
        
        public VtecTeamWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VtecTeamWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtecTeamWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtecTeamWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientAndServerCommons.AuthInfoResult Authenticate(string login, string passwordHash) {
            return base.Channel.Authenticate(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<ClientAndServerCommons.AuthInfoResult> AuthenticateAsync(string login, string passwordHash) {
            return base.Channel.AuthenticateAsync(login, passwordHash);
        }
        
        public void SignOut() {
            base.Channel.SignOut();
        }
        
        public System.Threading.Tasks.Task SignOutAsync() {
            return base.Channel.SignOutAsync();
        }
    }
}
